Libraries
Sklearn is a library with multiple modules used for manipulation of data

In [10]:
from sklearn import datasets
from sklearn.model_selection import train_test_split # to later separate the training sample from the testing sample based on a percentage
from sklearn.ensemble import RandomForestClassifier # to use the random forest classifier to build a simple model 
from sklearn.datasets import make_classification 

Loading the data

In [21]:
data = datasets.load_iris() # loading the dataset

In [25]:
print(data.feature_names) # getting our column or attribute names

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [27]:
print(data.target_names) # getting the names of our classes

['setosa' 'versicolor' 'virginica']


In [31]:
data.data # to see what the data looks like

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [35]:
data.target # to see the training or the class output ( 0 refers to setosa, 1 to versicolor and 2 to virginica)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [41]:
inp = data.data  # our input data
out = data.target # the output data we are training the model for

In [49]:
inp.shape

(150, 4)

In [51]:
out.shape

(150,)

In [55]:
model = RandomForestClassifier()

In [65]:
in_train, in_test, out_train, out_test = train_test_split(inp, out, test_size = 0.25) # separating the training data from the testing data

In [67]:
in_train.shape, out_train.shape # checking the size of the new training data

((112, 4), (112,))

In [69]:
in_test.shape, out_test.shape

((38, 4), (38,))

In [71]:
model.fit(in_train,out_train)

RandomForestClassifier()

In [73]:
print(model.predict([[5.9, 3. , 5.1, 1.8]]))

[2]


In [77]:
print(model.predict_proba([[5.9, 3. , 5.1, 1.8]]))

[[0.   0.11 0.89]]


In [79]:
print(model.predict(in_test))

[0 0 1 1 0 0 2 2 2 2 0 0 1 0 1 1 0 1 0 0 1 0 2 2 1 1 0 1 1 0 1 2 2 0 2 2 2
 1]


In [81]:
print(out_test)

[0 0 1 1 0 0 2 2 2 2 0 0 1 0 1 1 0 1 0 0 1 0 2 2 1 1 0 1 1 0 1 2 2 0 2 2 2
 1]


In [83]:
model.score(in_test, out_test)

1.0